version: '3.8'
services:
  flags-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: flags
      FLAGS_JSON_PATH: /app/data/flags.json
    volumes:
      - data_volume:/app/data

volumes:
  data_volume:
